### ISSUE TITLE
.

### ISSUE THREAD

**Issue by io-heart** [dustpg/SameFC#1]

**Comment by dustpg** [comment]
指的是哪啊, 说清楚啊╮（￣▽￣）╭

**Comment by agalis** [comment]
SameFC::PPU::Read

手柄的输入简单的就是一个锁区
1P操作就是IO4016 [此IO端口内部有两个元件(输入锁和移位计数器)]
读写分别有着不同的行为
写1 表示内部按键信息收集完备，做好准备等待输入，reset 内部计数器为0。输入锁锁定，但此时读端口无意义。【被锁定了】
写0解锁 ，解锁输入锁，内部计数器从零开始依次轮询按键信息 
此时才能读出正确的按键信息 ，一次只能读一个按键的信息 1为按下 0没按。每次读完之后计数器+1
每次接收到的按键缓冲信息有24位，前八位是手柄的信息。
D0-D7依次是 
A B SELECT START 上 下 左 右 
伪代码描述则是 
u8 read_joypad(void) {

	if (TRUE == PADs.bstrobe) 
	/*	lock ... 
				unable load immed ret zero */
		return 0;

	else if (FALSE == PADs.bstrobe) {
	/*	unlock ... 
				begin load input status	*/
		u8
		key_status = (*ngdDrvicer.joypadPointer >> PADs.sequence++) & 1;

		return key_status;
	}
	else 
	/*	otherwise ignorable treatmen */
		return; 
}

void write_joypad(s8 iCmd) {

	if (iCmd == LOCK_JOYPAD_BUFFER) {
	/*  lock input buf */ 
		PADs.bstrobe = TRUE; 
		PADs.sequence= 0; /* reset input sequence */
	}
	else if (iCmd == UNLOCK_JOYPAD_BUFFER) {
	/*	unlock input buf  */
		PADs.bstrobe = FALSE; /* unlock and closing gate */
	}
	else 
	/*	otherwise ignorable treatmen */
		return; 
}

**Comment by dustpg** [comment]
PPU现在还在弄寄存器, Read只是和CPU的Read名称一样而已, 方便上层FC直接调用, 读取的是CPU的地址.内部地址不对外公布接口, 只是设计上的事情而已.

**Comment by dustpg** [comment]
一个中转而已, 可以看看SameFC::Famicom::Read, 而CPU不能直接读取PPU数据, 得依靠$2006和$2007所以PPU的Read/Write并不是读写PPU的"内存", 而是PPU的寄存器. 根据个人习惯, 可能会将$2006,$2007操作封成read/write(小写开头表示内部函数), 而不是Read/Write(大写开头表示对外函数).

**Comment by agalis** [comment]
:)
